name: Example workflow for Python-3.8 using Snyk
on: push
jobs:
  security-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: https://api.eu.snyk.io
        with:
          args: --org=pipeline-examples --all-projects --severity-threshold=high
        continue-on-error: true



  security-monitor:
    runs-on: ubuntu-latest
    needs: security-test
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_API: https://api.eu.snyk.io
        with:
          command: monitor
          args: --org=pipeline-examples --all-projects
